use_frameworks!

platform :ios, '9.0'

target 'StateSubject_Example' do
  pod 'StateSubject', :path => '../'

  target 'StateSubject_Tests' do
    inherit! :search_paths
    pod 'RxBlocking'
    
  end
end
